server:
    port: 8080
spring:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      hibernate.show_sql: false
      hibernate.format_sql: false
      hibernate.hbm2ddl.auto: update
      hibernate.enable_lazy_load_no_trans: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/phonebook?useSSL=false&useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: root
  thymeleaf:
    mode: LEGACYHTML5
    suffix: .html
    encoding: UTF-8
    content-type: text/html



